import { execFile } from 'node:child_process'
import { existsSync } from 'node:fs'
import { mkdir, readdir, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { promisify } from 'node:util'
import { readIgnoreRuleLines, skippedDirectories } from './toolBroker.mjs'

/**
 * The checkpoint store: one private shadow Git repository per bridge, with the
 * live workspace as its work tree (ADR 0010). It never writes into the
 * workspace, never consults the user's Git configuration, and its vocabulary
 * is the same one the tools obey.
 *
 * The index lives in the data directory and persists across restarts, so a
 * commit after adding only the paths a write touched still snapshots the whole
 * tree: a checkpoint costs the size of the change, not the size of the tree.
 */

const execFileAsync = promisify(execFile)
const nullDevice = process.platform === 'win32' ? 'NUL' : '/dev/null'
const MAX_GIT_OUTPUT = 10 * 1024 * 1024

// A gitignore mirror of permissions.mjs sensitiveFilePattern (line 13). Kept
// as literal patterns because gitignore cannot express a regex; the checkpoint
// suite pins each one so a change over there shows up here.
const SENSITIVE_EXCLUDES = [
  '.env*',
  '.npmrc',
  '.netrc',
  '.git-credentials',
  'credentials*',
  'kubeconfig',
  'id_rsa',
  'id_rsa.pub',
  'id_dsa',
  'id_dsa.pub',
  'id_ecdsa',
  'id_ecdsa.pub',
  'id_ed25519',
  'id_ed25519.pub',
  '*.pem',
  '*.key',
  '*.p12',
  '*.pfx',
  '*.jks',
  '*.keystore',
  '*.ppk',
  '*.sqlite',
  '*.sqlite-shm',
  '*.sqlite-wal',
  '*.db',
]

async function directoryBytes(directory) {
  let total = 0
  let entries
  try {
    entries = await readdir(directory, { withFileTypes: true })
  } catch {
    return 0
  }
  for (const entry of entries) {
    const full = path.join(directory, entry.name)
    if (entry.isDirectory()) total += await directoryBytes(full)
    else {
      try {
        total += (await stat(full)).size
      } catch {
        // A file that vanished mid-walk contributes nothing, not a crash.
      }
    }
  }
  return total
}

/**
 * @param {{ workspaceRoot: string, dataDir: string, execFileImpl?: (file: string, args: string[], options: Record<string, unknown>) => Promise<{ stdout?: string | Buffer, stderr?: string | Buffer }> }} options
 */
export function createCheckpointStore({ workspaceRoot, dataDir, execFileImpl = execFileAsync }) {
  const root = path.resolve(workspaceRoot)
  const checkpointsDir = path.join(path.resolve(dataDir), 'checkpoints')
  const gitDir = path.join(checkpointsDir, 'repo.git')
  const indexFile = path.join(checkpointsDir, 'index')
  let availability = null

  // Every invocation is neutralized: the host's global and system config are
  // pointed at the null device, hooks and prompts are off, and the repository
  // state (git dir, work tree, index) is stated explicitly rather than
  // discovered.
  const gitEnv = () => ({
    ...process.env,
    GIT_DIR: gitDir,
    GIT_WORK_TREE: root,
    GIT_INDEX_FILE: indexFile,
    GIT_CONFIG_GLOBAL: nullDevice,
    GIT_CONFIG_SYSTEM: nullDevice,
    GIT_CONFIG_NOSYSTEM: '1',
    GIT_TERMINAL_PROMPT: '0',
  })

  const run = async (args, { timeoutMs = 30_000 } = {}) => {
    const result = await execFileImpl('git', args, { cwd: root, env: gitEnv(), windowsHide: true, timeout: timeoutMs, maxBuffer: MAX_GIT_OUTPUT })
    return { stdout: String(result.stdout ?? ''), stderr: String(result.stderr ?? '') }
  }

  const available = async () => {
    if (availability) return availability
    try {
      const result = await run(['--version'], { timeoutMs: 10_000 })
      availability = { ok: true, version: result.stdout.trim() || 'git' }
    } catch (error) {
      const detail = error instanceof Error && error.message ? error.message : 'the command failed'
      availability = { ok: false, reason: `Host Git is not available: ${detail}. Writing runs need Git so every write can be checkpointed (ADR 0010).` }
    }
    return availability
  }

  const excludeVocabulary = async () => {
    const lines = [
      '# Generated by Fulkrum. Do not edit: the vocabulary mirrors the tool',
      '# boundary \u2014 skipped directories (toolBroker.mjs), sensitive files',
      '# (permissions.mjs), the data directory, and the workspace .fulkrumignore.',
    ]
    for (const directory of skippedDirectories) lines.push(`${directory}/`)
    lines.push(...SENSITIVE_EXCLUDES)
    const relativeData = path.relative(root, path.resolve(dataDir))
    if (relativeData && !relativeData.startsWith('..') && !path.isAbsolute(relativeData)) {
      lines.push(`${relativeData.split(path.sep).join('/')}/`)
    }
    lines.push(...(await readIgnoreRuleLines(root)))
    return `${lines.join('\n')}\n`
  }

  const ensure = async () => {
    const probe = await available()
    if (!probe.ok) throw new Error(probe.reason)
    if (existsSync(path.join(gitDir, 'HEAD'))) return { initialized: true, created: false, gitDir, indexFile }
    await mkdir(checkpointsDir, { recursive: true })
    await run(['init', '--quiet'])
    const config = [
      ['core.worktree', root],
      ['core.bare', 'false'],
      ['core.autocrlf', 'false'],
      ['core.fileMode', 'false'],
      ['core.quotepath', 'false'],
      ['core.hooksPath', path.join(gitDir, 'no-hooks')],
      ['commit.gpgsign', 'false'],
      ['user.name', 'Fulkrum'],
      ['user.email', 'fulkrum@localhost'],
    ]
    for (const [key, value] of config) await run(['config', key, value])
    await writeFile(path.join(gitDir, 'info', 'exclude'), await excludeVocabulary())
    return { initialized: true, created: true, gitDir, indexFile }
  }

  const status = async () => {
    const probe = await available()
    const initialized = probe.ok && existsSync(path.join(gitDir, 'HEAD'))
    let checkpoints = 0
    let latest = null
    if (initialized) {
      try {
        checkpoints = Number((await run(['rev-list', '--count', 'HEAD'])).stdout.trim()) || 0
        latest = (await run(['log', '-1', '--format=%H %ct'])).stdout.trim() || null
      } catch {
        // An initialized repository with no commit yet has zero checkpoints.
        checkpoints = 0
        latest = null
      }
    }
    return {
      available: probe.ok,
      version: probe.ok ? probe.version : null,
      reason: probe.ok ? null : probe.reason,
      initialized,
      checkpoints,
      latest,
      bytes: await directoryBytes(checkpointsDir),
      gitDir,
      indexFile,
    }
  }

  const checkpoint = async ({ paths = [], message = 'checkpoint', runId = null, taskId = null, toolCallId = null }) => {
    await ensure()
    const relative = paths
      .map((entry) => path.relative(root, path.resolve(root, entry)).split(path.sep).join('/'))
      .filter((entry) => entry && !entry.startsWith('..') && !path.isAbsolute(entry))
    if (!relative.length) return { commit: null, unchanged: true, files: 0 }
    // A write into an excluded path (dist output, node_modules) is legitimate
    // and simply not checkpointed — `git add` would refuse it outright, which
    // must not fail the run.
    let ignored = []
    try {
      ignored = (await run(['check-ignore', '--', ...relative])).stdout.split('\n').map((line) => line.trim()).filter(Boolean)
    } catch (error) {
      // Exit 1 means "nothing ignored"; anything else is a real failure.
      if (error?.code !== 1) throw error
    }
    const tracked = relative.filter((entry) => !ignored.includes(entry))
    if (!tracked.length) return { commit: null, unchanged: true, files: 0, ignored }
    await run(['add', '--all', '--', ...tracked])
    const subject = [message, runId ? `run ${runId}` : null, taskId ? `task ${taskId}` : null, toolCallId ? `call ${toolCallId}` : null].filter(Boolean).join(' \u00b7 ')
    try {
      await run(['commit', '--quiet', '--no-verify', '-m', subject])
    } catch (error) {
      const detail = [error?.stdout, error?.stderr, error instanceof Error ? error.message : ''].map((part) => String(part ?? '')).join('\n')
      // An unchanged write stages nothing; that is a fact, not a failure.
      if (/nothing to commit|nothing added to commit|no changes added to commit/i.test(detail)) return { commit: null, unchanged: true, files: tracked.length, message: subject, ignored }
      throw error
    }
    const commit = (await run(['rev-parse', 'HEAD'])).stdout.trim()
    return { commit, unchanged: false, files: tracked.length, message: subject }
  }

  return { run, available, ensure, checkpoint, status, workspaceRoot: root, dataDir: path.resolve(dataDir), gitDir, indexFile }
}

/**
 * The bridge between a write and its checkpoint, shared by both execution
 * paths (the worker loop and the direct tools API). ADR 0010: host Git is a
 * hard requirement for write runs, and a write that cannot be checkpointed
 * interrupts the run instead of continuing over unrecorded state.
 */
export function createWriteCheckpointer({ store, checkpoints }) {
  if (!checkpoints) return null
  const assertReady = async () => {
    const ready = await checkpoints.available()
    if (!ready.ok) throw new Error(ready.reason)
  }
  const afterWrite = async ({ runId, taskId = null, agentId = null, toolCallId, path: writtenPath }) => {
    let result
    try {
      result = await checkpoints.checkpoint({ paths: [writtenPath], message: `write ${writtenPath}`, runId, taskId, toolCallId })
    } catch (error) {
      const detail = error instanceof Error && error.message ? error.message : 'the checkpoint failed'
      const reason = `The write to ${writtenPath} could not be checkpointed: ${detail}`
      store.updateRun(runId, { status: 'interrupted', interruptedFrom: 'executing' })
      store.markRunInterrupted(runId, reason)
      throw new Error(reason)
    }
    if (result.commit) {
      store.appendEvent({ runId, type: 'checkpoint.created', agentId: agentId ?? 'head', payload: { toolCallId, commit: result.commit, path: writtenPath } })
    }
    return result
  }
  return { assertReady, afterWrite }
}
