import { execFile } from 'node:child_process'
import { existsSync } from 'node:fs'
import { mkdir, readdir, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { promisify } from 'node:util'
import { readIgnoreRuleLines, skippedDirectories } from './toolBroker.mjs'

/**
 * The checkpoint store: one private shadow Git repository per bridge, with the
 * live workspace as its work tree (ADR 0010). It never writes into the
 * workspace, never consults the user's Git configuration, and its vocabulary
 * is the same one the tools obey.
 *
 * The index lives in the data directory and persists across restarts, so a
 * commit after adding only the paths a write touched still snapshots the whole
 * tree: a checkpoint costs the size of the change, not the size of the tree.
 */

const execFileAsync = promisify(execFile)
const nullDevice = process.platform === 'win32' ? 'NUL' : '/dev/null'
const MAX_GIT_OUTPUT = 10 * 1024 * 1024

// A gitignore mirror of permissions.mjs sensitiveFilePattern (line 13). Kept
// as literal patterns because gitignore cannot express a regex; the checkpoint
// suite pins each one so a change over there shows up here.
const SENSITIVE_EXCLUDES = [
  '.env*',
  '.npmrc',
  '.netrc',
  '.git-credentials',
  'credentials*',
  'kubeconfig',
  'id_rsa',
  'id_rsa.pub',
  'id_dsa',
  'id_dsa.pub',
  'id_ecdsa',
  'id_ecdsa.pub',
  'id_ed25519',
  'id_ed25519.pub',
  '*.pem',
  '*.key',
  '*.p12',
  '*.pfx',
  '*.jks',
  '*.keystore',
  '*.ppk',
  '*.sqlite',
  '*.sqlite-shm',
  '*.sqlite-wal',
  '*.db',
]

async function directoryBytes(directory) {
  let total = 0
  let entries
  try {
    entries = await readdir(directory, { withFileTypes: true })
  } catch {
    return 0
  }
  for (const entry of entries) {
    const full = path.join(directory, entry.name)
    if (entry.isDirectory()) total += await directoryBytes(full)
    else {
      try {
        total += (await stat(full)).size
      } catch {
        // A file that vanished mid-walk contributes nothing, not a crash.
      }
    }
  }
  return total
}

/**
 * @param {{ workspaceRoot: string, dataDir: string, execFileImpl?: (file: string, args: string[], options: Record<string, unknown>) => Promise<{ stdout?: string | Buffer, stderr?: string | Buffer }> }} options
 */
export function createCheckpointStore({ workspaceRoot, dataDir, execFileImpl = execFileAsync }) {
  const root = path.resolve(workspaceRoot)
  const checkpointsDir = path.join(path.resolve(dataDir), 'checkpoints')
  const gitDir = path.join(checkpointsDir, 'repo.git')
  const indexFile = path.join(checkpointsDir, 'index')
  let availability = null

  // Every invocation is neutralized: the host's global and system config are
  // pointed at the null device, hooks and prompts are off, and the repository
  // state (git dir, work tree, index) is stated explicitly rather than
  // discovered.
  const gitEnv = () => ({
    ...process.env,
    GIT_DIR: gitDir,
    GIT_WORK_TREE: root,
    GIT_INDEX_FILE: indexFile,
    GIT_CONFIG_GLOBAL: nullDevice,
    GIT_CONFIG_SYSTEM: nullDevice,
    GIT_CONFIG_NOSYSTEM: '1',
    GIT_TERMINAL_PROMPT: '0',
  })

  const run = async (args, { timeoutMs = 30_000 } = {}) => {
    const result = await execFileImpl('git', args, { cwd: root, env: gitEnv(), windowsHide: true, timeout: timeoutMs, maxBuffer: MAX_GIT_OUTPUT })
    return { stdout: String(result.stdout ?? ''), stderr: String(result.stderr ?? '') }
  }

  const available = async () => {
    if (availability) return availability
    try {
      const result = await run(['--version'], { timeoutMs: 10_000 })
      availability = { ok: true, version: result.stdout.trim() || 'git' }
    } catch (error) {
      const detail = error instanceof Error && error.message ? error.message : 'the command failed'
      availability = { ok: false, reason: `Host Git is not available: ${detail}. Writing runs need Git so every write can be checkpointed (ADR 0010).` }
    }
    return availability
  }

  const excludeVocabulary = async () => {
    const lines = [
      '# Generated by Fulkrum. Do not edit: the vocabulary mirrors the tool',
      '# boundary \u2014 skipped directories (toolBroker.mjs), sensitive files',
      '# (permissions.mjs), the data directory, and the workspace .fulkrumignore.',
    ]
    for (const directory of skippedDirectories) lines.push(`${directory}/`)
    lines.push(...SENSITIVE_EXCLUDES)
    const relativeData = path.relative(root, path.resolve(dataDir))
    if (relativeData && !relativeData.startsWith('..') && !path.isAbsolute(relativeData)) {
      lines.push(`${relativeData.split(path.sep).join('/')}/`)
    }
    lines.push(...(await readIgnoreRuleLines(root)))
    return `${lines.join('\n')}\n`
  }

  const ensure = async () => {
    const probe = await available()
    if (!probe.ok) throw new Error(probe.reason)
    if (existsSync(path.join(gitDir, 'HEAD'))) return { initialized: true, created: false, gitDir, indexFile }
    await mkdir(checkpointsDir, { recursive: true })
    await run(['init', '--quiet'])
    const config = [
      ['core.worktree', root],
      ['core.bare', 'false'],
      ['core.autocrlf', 'false'],
      ['core.fileMode', 'false'],
      ['core.quotepath', 'false'],
      ['core.hooksPath', path.join(gitDir, 'no-hooks')],
      ['commit.gpgsign', 'false'],
      ['user.name', 'Fulkrum'],
      ['user.email', 'fulkrum@localhost'],
    ]
    for (const [key, value] of config) await run(['config', key, value])
    await writeFile(path.join(gitDir, 'info', 'exclude'), await excludeVocabulary())
    return { initialized: true, created: true, gitDir, indexFile }
  }

  const status = async () => {
    const probe = await available()
    const initialized = probe.ok && existsSync(path.join(gitDir, 'HEAD'))
    let checkpoints = 0
    let latest = null
    if (initialized) {
      try {
        checkpoints = Number((await run(['rev-list', '--count', 'HEAD'])).stdout.trim()) || 0
        latest = (await run(['log', '-1', '--format=%H %ct'])).stdout.trim() || null
      } catch {
        // An initialized repository with no commit yet has zero checkpoints.
        checkpoints = 0
        latest = null
      }
    }
    return {
      available: probe.ok,
      version: probe.ok ? probe.version : null,
      reason: probe.ok ? null : probe.reason,
      initialized,
      checkpoints,
      latest,
      bytes: await directoryBytes(checkpointsDir),
      gitDir,
      indexFile,
    }
  }

  return { run, available, ensure, status, workspaceRoot: root, dataDir: path.resolve(dataDir), gitDir, indexFile }
}
