import { execFile } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { promisify } from 'node:util'
import { readIgnoreRuleLines, skippedDirectories } from './toolBroker.mjs'

/**
 * The checkpoint store: one private shadow Git repository per bridge, with the
 * live workspace as its work tree (ADR 0010). It never writes into the
 * workspace, never consults the user's Git configuration, and its vocabulary
 * is the same one the tools obey.
 *
 * The index lives in the data directory and persists across restarts, so a
 * commit after adding only the paths a write touched still snapshots the whole
 * tree: a checkpoint costs the size of the change, not the size of the tree.
 */

const execFileAsync = promisify(execFile)
const nullDevice = process.platform === 'win32' ? 'NUL' : '/dev/null'
const MAX_GIT_OUTPUT = 10 * 1024 * 1024

// A gitignore mirror of permissions.mjs sensitiveFilePattern (line 13). Kept
// as literal patterns because gitignore cannot express a regex; the checkpoint
// suite pins each one so a change over there shows up here.
const SENSITIVE_EXCLUDES = [
  '.env*',
  '.npmrc',
  '.netrc',
  '.git-credentials',
  'credentials*',
  'kubeconfig',
  'id_rsa',
  'id_rsa.pub',
  'id_dsa',
  'id_dsa.pub',
  'id_ecdsa',
  'id_ecdsa.pub',
  'id_ed25519',
  'id_ed25519.pub',
  '*.pem',
  '*.key',
  '*.p12',
  '*.pfx',
  '*.jks',
  '*.keystore',
  '*.ppk',
  '*.sqlite',
  '*.sqlite-shm',
  '*.sqlite-wal',
  '*.db',
]

async function readGitignoreLines(root) {
  try {
    const text = await readFile(path.join(root, '.gitignore'), 'utf8')
    return text
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'))
  } catch {
    return []
  }
}

async function directoryBytes(directory) {
  let total = 0
  let entries
  try {
    entries = await readdir(directory, { withFileTypes: true })
  } catch {
    return 0
  }
  for (const entry of entries) {
    const full = path.join(directory, entry.name)
    if (entry.isDirectory()) total += await directoryBytes(full)
    else {
      try {
        total += (await stat(full)).size
      } catch {
        // A file that vanished mid-walk contributes nothing, not a crash.
      }
    }
  }
  return total
}

/**
 * @param {{ workspaceRoot: string, dataDir: string, execFileImpl?: (file: string, args: string[], options: Record<string, unknown>) => Promise<{ stdout?: string | Buffer, stderr?: string | Buffer }> }} options
 */
export function createCheckpointStore({ workspaceRoot, dataDir, execFileImpl = execFileAsync }) {
  const root = path.resolve(workspaceRoot)
  const checkpointsDir = path.join(path.resolve(dataDir), 'checkpoints')
  const gitDir = path.join(checkpointsDir, 'repo.git')
  const indexFile = path.join(checkpointsDir, 'index')
  let availability = null

  // Every invocation is neutralized: the host's global and system config are
  // pointed at the null device, hooks and prompts are off, and the repository
  // state (git dir, work tree, index) is stated explicitly rather than
  // discovered.
  const gitEnv = () => ({
    ...process.env,
    GIT_DIR: gitDir,
    GIT_WORK_TREE: root,
    GIT_INDEX_FILE: indexFile,
    GIT_CONFIG_GLOBAL: nullDevice,
    GIT_CONFIG_SYSTEM: nullDevice,
    GIT_CONFIG_NOSYSTEM: '1',
    GIT_TERMINAL_PROMPT: '0',
  })

  const run = async (args, { timeoutMs = 30_000 } = {}) => {
    const result = await execFileImpl('git', args, { cwd: root, env: gitEnv(), windowsHide: true, timeout: timeoutMs, maxBuffer: MAX_GIT_OUTPUT })
    return { stdout: String(result.stdout ?? ''), stderr: String(result.stderr ?? '') }
  }

  const available = async () => {
    if (availability) return availability
    try {
      const result = await run(['--version'], { timeoutMs: 10_000 })
      availability = { ok: true, version: result.stdout.trim() || 'git' }
    } catch (error) {
      const detail = error instanceof Error && error.message ? error.message : 'the command failed'
      availability = { ok: false, reason: `Host Git is not available: ${detail}. Writing runs need Git so every write can be checkpointed (ADR 0010).` }
    }
    return availability
  }

  const excludeVocabulary = async () => {
    const lines = [
      '# Generated by Fulkrum. Do not edit: the vocabulary mirrors the tool',
      '# boundary \u2014 skipped directories (toolBroker.mjs), sensitive files',
      '# (permissions.mjs), the data directory, the workspace .fulkrumignore,',
      '# and the workspace .gitignore.',
    ]
    for (const directory of skippedDirectories) lines.push(`${directory}/`)
    lines.push(...SENSITIVE_EXCLUDES)
    const relativeData = path.relative(root, path.resolve(dataDir))
    if (relativeData && !relativeData.startsWith('..') && !path.isAbsolute(relativeData)) {
      lines.push(`${relativeData.split(path.sep).join('/')}/`)
    }
    lines.push(...(await readIgnoreRuleLines(root)))
    lines.push(...(await readGitignoreLines(root)))
    return `${lines.join('\n')}\n`
  }

  // The vocabulary can change between runs (.gitignore edited), so it is
  // refreshed before every baseline, not only at initialization.
  const refreshExclude = async () => {
    await writeFile(path.join(gitDir, 'info', 'exclude'), await excludeVocabulary())
  }

  const ensure = async () => {
    const probe = await available()
    if (!probe.ok) throw new Error(probe.reason)
    if (existsSync(path.join(gitDir, 'HEAD'))) return { initialized: true, created: false, gitDir, indexFile }
    await mkdir(checkpointsDir, { recursive: true })
    await run(['init', '--quiet'])
    const config = [
      ['core.worktree', root],
      ['core.bare', 'false'],
      ['core.autocrlf', 'false'],
      ['core.fileMode', 'false'],
      ['core.quotepath', 'false'],
      ['core.hooksPath', path.join(gitDir, 'no-hooks')],
      ['commit.gpgsign', 'false'],
      ['user.name', 'Fulkrum'],
      ['user.email', 'fulkrum@localhost'],
    ]
    for (const [key, value] of config) await run(['config', key, value])
    await refreshExclude()
    return { initialized: true, created: true, gitDir, indexFile }
  }

  /**
   * Stage and commit everything covered, whatever changed since the last
   * commit. Reuses the tip when nothing staged; creates the root commit when
   * the covered tree is empty and no tip exists — a snapshot must always
   * resolve to a commit, or later diffs have no base.
   */
  const snapshot = async ({ message = 'snapshot' }) => {
    await ensure()
    await refreshExclude()
    await run(['add', '--all'])
    const staged = (await run(['diff', '--cached', '--name-only'])).stdout.split('\n').map((line) => line.trim()).filter(Boolean)
    let commit
    if (staged.length) {
      await run(['commit', '--quiet', '--no-verify', '-m', message])
      commit = (await run(['rev-parse', 'HEAD'])).stdout.trim()
    } else {
      try {
        commit = (await run(['rev-parse', 'HEAD'])).stdout.trim()
      } catch {
        await run(['commit', '--quiet', '--no-verify', '--allow-empty', '-m', message])
        commit = (await run(['rev-parse', 'HEAD'])).stdout.trim()
      }
    }
    return { commit, files: staged.length }
  }

  /**
   * The run-start checkpoint (P1.1): a full snapshot of covered content,
   * taken before any work, with one private ref per run so the baseline
   * survives restarts and a resumed run keeps its original. A second call
   * for the same run is a no-op that reports the existing ref.
   */
  const baseline = async ({ runId }) => {
    await ensure()
    const safeRunId = typeof runId === 'string' && /^[A-Za-z0-9._-]+$/.test(runId) ? runId : null
    const ref = safeRunId ? `refs/runs/${safeRunId}` : null
    if (ref) {
      try {
        const existing = (await run(['rev-parse', '--verify', '--quiet', ref])).stdout.trim()
        if (existing) return { commit: existing, files: 0, reused: true, largeTree: false }
      } catch {
        // No ref yet: take the baseline below.
      }
    }
    const result = await snapshot({ message: `run start${safeRunId ? ` \u00b7 run ${safeRunId}` : ''}` })
    if (ref && result.commit) await run(['update-ref', ref, result.commit])
    // A large first snapshot is expensive; reporting it beats pretending the
    // cost is not there (P1.1).
    const largeTreeThreshold = Math.max(Number(process.env.FULKRUM_CHECKPOINT_LARGE_TREE_FILES ?? 10_000) || 10_000, 1)
    return { ...result, reused: false, largeTree: result.files > largeTreeThreshold }
  }

  /**
   * Discard a run's covered changes: restore every path the baseline→final
   * diff names back to its baseline state, but never overwrite a file that
   * moved after the run ended. The current live bytes must equal the final
   * snapshot's bytes for a path to be touched at all; anything else is a
   * conflict, listed and left alone. A path the run created is removed, not
   * left behind. The result is snapshotted so the discard is itself history.
   *
   * Text comparison: binary files compare as text and therefore mismatch
   * safely — they are reported as conflicts rather than guessed at.
   */
  const discardChanges = async ({ baseline, final, paths = null }) => {
    await ensure()
    const changed = await diff({ from: baseline, to: final })
    const selected = paths?.length ? changed.filter((entry) => paths.includes(entry.path)) : changed
    const contentAt = async (commit, relative) => {
      try {
        return (await run(['show', `${commit}:${relative}`])).stdout
      } catch {
        return null
      }
    }
    const liveContent = (relative) => {
      try {
        return readFileSync(path.join(root, relative), 'utf8')
      } catch {
        return null
      }
    }
    const restored = []
    const removed = []
    const skipped = []
    for (const entry of selected) {
      const live = liveContent(entry.path)
      const expected = await contentAt(final, entry.path)
      if (live !== expected) {
        skipped.push({ path: entry.path, reason: 'changed since the run ended' })
        continue
      }
      const original = await contentAt(baseline, entry.path)
      if (original === null) {
        await rm(path.join(root, entry.path), { force: true })
        removed.push(entry.path)
      } else {
        await run(['checkout', baseline, '--', entry.path])
        restored.push(entry.path)
      }
    }
    const after = await snapshot({ message: `discard \u00b7 run ${String(baseline).slice(0, 8)}` })
    return { restored, removed, skipped, commit: after.commit }
  }

  /**
   * Prune the checkpoint refs of runs whose decision is complete and old
   * enough, then drop the unreferenced objects (P1.1). Undecided runs are
   * never in the list the caller passes: a checkpoint needed for a pending
   * review, undo, or discard is not prunable. Reports what it released and
   * the store size before and after.
   */
  const prune = async ({ releaseRunIds = [] }) => {
    await ensure()
    const before = await directoryBytes(checkpointsDir)
    const released = []
    for (const runId of releaseRunIds) {
      const safeRunId = typeof runId === 'string' && /^[A-Za-z0-9._-]+$/.test(runId) ? runId : null
      if (!safeRunId) continue
      const ref = `refs/runs/${safeRunId}`
      try {
        await run(['rev-parse', '--verify', '--quiet', ref])
      } catch {
        continue
      }
      await run(['update-ref', '-d', ref])
      released.push(safeRunId)
    }
    if (released.length) {
      try {
        await run(['reflog', 'expire', '--expire=now', '--all'])
      } catch {
        // No reflog yet is not a failure.
      }
      await run(['gc', '--prune=now', '--quiet'])
    }
    return { released, bytesBefore: before, bytesAfter: await directoryBytes(checkpointsDir) }
  }

  /** The covered-file changes between two snapshots, as a reproducible diff. */
  const diff = async ({ from, to }) => {
    const status = (await run(['diff', '--name-status', from, to])).stdout
    const numstat = (await run(['diff', '--numstat', from, to])).stdout
    const counts = new Map()
    for (const line of numstat.split('\n')) {
      const [added, removed, ...rest] = line.split('\t')
      const filePath = rest.join('\t')
      if (filePath) counts.set(filePath, { added: added === '-' ? null : Number(added), removed: removed === '-' ? null : Number(removed) })
    }
    return status.split('\n').map((line) => line.trim()).filter(Boolean).map((line) => {
      const parts = line.split('\t')
      const kind = parts[0]?.[0]
      const filePath = parts.at(-1) ?? ''
      return {
        path: filePath,
        change: kind === 'A' ? 'added' : kind === 'D' ? 'deleted' : kind === 'R' ? 'renamed' : 'modified',
        ...(counts.get(filePath) ?? { added: null, removed: null }),
      }
    })
  }

  /**
   * Which of the diffed paths moved after the run's final snapshot. A conflict
   * is shown, never overwritten: the same comparison the discard uses.
   */
  const markConflicts = async ({ final, files }) => {
    const out = []
    for (const entry of files) {
      let live = null
      try {
        live = readFileSync(path.join(root, entry.path), 'utf8')
      } catch {
        live = null
      }
      let expected = null
      try {
        expected = (await run(['show', `${final}:${entry.path}`])).stdout
      } catch {
        expected = null
      }
      out.push({ ...entry, conflict: live !== expected })
    }
    return out
  }

  const changedPaths = async (commit) => {
    const output = (await run(['show', '--name-only', '--format=', commit])).stdout
    return output.split('\n').map((line) => line.trim()).filter(Boolean)
  }

  /** The recent checkpoints, newest first, for the restore surface. */
  const list = async ({ limit = 50 } = {}) => {
    const probe = await available()
    if (!probe.ok || !existsSync(path.join(gitDir, 'HEAD'))) return []
    const capped = Math.max(1, Math.min(Number(limit) || 50, 200))
    try {
      const output = (await run(['log', `--max-count=${capped}`, '--format=%H%x1f%ct%x1f%s'])).stdout
      const entries = []
      for (const line of output.split('\n')) {
        const trimmed = line.trim()
        if (!trimmed) continue
        const [commit, at, subject] = trimmed.split('\x1f')
        entries.push({ commit, at: Number(at) * 1000, subject: subject ?? '' })
      }
      return entries
    } catch {
      return []
    }
  }

  /**
   * Restore the paths one checkpoint touched, back to that checkpoint's bytes.
   * The current state is checkpointed first, so a restore is itself undoable,
   * and the restored state is committed so history never rewinds (ADR 0010).
   */
  const restore = async ({ commit, paths = null, runId = null }) => {
    await ensure()
    await run(['cat-file', '-e', `${commit}^{commit}`])
    const targets = paths?.length ? paths : await changedPaths(commit)
    const relative = targets
      .map((entry) => path.relative(root, path.resolve(root, entry)).split(path.sep).join('/'))
      .filter((entry) => entry && !entry.startsWith('..') && !path.isAbsolute(entry))
    if (!relative.length) throw new Error('Nothing to restore.')
    await checkpoint({ paths: relative, message: 'pre-restore' })
    await run(['checkout', commit, '--', ...relative])
    const result = await checkpoint({ paths: relative, message: `restore ${String(commit).slice(0, 8)}`, runId })
    return { from: commit, commit: result.commit, paths: relative, unchanged: result.unchanged }
  }

  const status = async () => {
    const probe = await available()
    const initialized = probe.ok && existsSync(path.join(gitDir, 'HEAD'))
    let checkpoints = 0
    let latest = null
    if (initialized) {
      try {
        checkpoints = Number((await run(['rev-list', '--count', 'HEAD'])).stdout.trim()) || 0
        latest = (await run(['log', '-1', '--format=%H %ct'])).stdout.trim() || null
      } catch {
        // An initialized repository with no commit yet has zero checkpoints.
        checkpoints = 0
        latest = null
      }
    }
    return {
      available: probe.ok,
      version: probe.ok ? probe.version : null,
      reason: probe.ok ? null : probe.reason,
      initialized,
      checkpoints,
      latest,
      bytes: await directoryBytes(checkpointsDir),
      gitDir,
      indexFile,
    }
  }

  const checkpoint = async ({ paths = [], message = 'checkpoint', runId = null, taskId = null, toolCallId = null }) => {
    await ensure()
    const relative = paths
      .map((entry) => path.relative(root, path.resolve(root, entry)).split(path.sep).join('/'))
      .filter((entry) => entry && !entry.startsWith('..') && !path.isAbsolute(entry))
    if (!relative.length) return { commit: null, unchanged: true, files: 0 }
    // A write into an excluded path (dist output, node_modules) is legitimate
    // and simply not checkpointed — `git add` would refuse it outright, which
    // must not fail the run.
    let ignored = []
    try {
      ignored = (await run(['check-ignore', '--', ...relative])).stdout.split('\n').map((line) => line.trim()).filter(Boolean)
    } catch (error) {
      // Exit 1 means "nothing ignored"; anything else is a real failure.
      if (error?.code !== 1) throw error
    }
    const tracked = relative.filter((entry) => !ignored.includes(entry))
    if (!tracked.length) return { commit: null, unchanged: true, files: 0, ignored }
    await run(['add', '--all', '--', ...tracked])
    const subject = [message, runId ? `run ${runId}` : null, taskId ? `task ${taskId}` : null, toolCallId ? `call ${toolCallId}` : null].filter(Boolean).join(' \u00b7 ')
    try {
      await run(['commit', '--quiet', '--no-verify', '-m', subject])
    } catch (error) {
      const detail = [error?.stdout, error?.stderr, error instanceof Error ? error.message : ''].map((part) => String(part ?? '')).join('\n')
      // An unchanged write stages nothing; that is a fact, not a failure.
      if (/nothing to commit|nothing added to commit|no changes added to commit/i.test(detail)) return { commit: null, unchanged: true, files: tracked.length, message: subject, ignored }
      throw error
    }
    const commit = (await run(['rev-parse', 'HEAD'])).stdout.trim()
    return { commit, unchanged: false, files: tracked.length, message: subject }
  }

  return { run, available, ensure, checkpoint, snapshot, baseline, diff, markConflicts, discardChanges, prune, list, restore, status, workspaceRoot: root, dataDir: path.resolve(dataDir), gitDir, indexFile }
}

/**
 * The bridge between a write and its checkpoint, shared by both execution
 * paths (the worker loop and the direct tools API). ADR 0010: host Git is a
 * hard requirement for write runs, and a write that cannot be checkpointed
 * interrupts the run instead of continuing over unrecorded state.
 */
export function createWriteCheckpointer({ store, checkpoints }) {
  if (!checkpoints) return null
  const assertReady = async () => {
    const ready = await checkpoints.available()
    if (!ready.ok) throw new Error(ready.reason)
  }
  const afterWrite = async ({ runId, taskId = null, agentId = null, toolCallId, path: writtenPath }) => {
    let result
    try {
      result = await checkpoints.checkpoint({ paths: [writtenPath], message: `write ${writtenPath}`, runId, taskId, toolCallId })
    } catch (error) {
      const detail = error instanceof Error && error.message ? error.message : 'the checkpoint failed'
      const reason = `The write to ${writtenPath} could not be checkpointed: ${detail}`
      store.updateRun(runId, { status: 'interrupted', interruptedFrom: 'executing' })
      store.markRunInterrupted(runId, reason)
      throw new Error(reason)
    }
    if (result.commit) {
      store.appendEvent({ runId, type: 'checkpoint.created', agentId: agentId ?? 'head', payload: { toolCallId, commit: result.commit, path: writtenPath } })
    }
    return result
  }
  const baseline = ({ runId }) => checkpoints.baseline({ runId })
  /** The run-end snapshot (P1.2): what the covered folder held when the run stopped moving. */
  const finalize = async ({ runId, agentId = 'head' }) => {
    const result = await checkpoints.snapshot({ message: `run end \u00b7 run ${runId}` })
    store.appendEvent({ runId, type: 'checkpoint.final', agentId, payload: { commit: result.commit, files: result.files, at: Date.now() } })
    return result
  }
  /**
   * After every shell command, including failed ones (P1.2): the receipt
   * names the changed paths; this snapshots them so the change is on the
   * chain even when the command exited nonzero. Attribution is an interval,
   * not a proof: the event says "changed during this command", never "caused
   * by it".
   */
  const afterShell = async ({ runId, taskId = null, agentId = null, toolCallId, changedFiles }) => {
    const paths = [...(changedFiles?.added ?? []), ...(changedFiles?.modified ?? []), ...(changedFiles?.removed ?? [])].filter((entry) => typeof entry === 'string' && entry)
    if (!paths.length) return { commit: null, unchanged: true, files: 0 }
    let result
    try {
      result = await checkpoints.checkpoint({ paths, message: `shell changed ${paths.length} path(s)`, runId, taskId, toolCallId })
    } catch (error) {
      const detail = error instanceof Error && error.message ? error.message : 'the checkpoint failed'
      const reason = `The shell command's changes could not be checkpointed: ${detail}`
      store.appendEvent({ runId, type: 'checkpoint.failed', agentId: agentId ?? 'head', payload: { source: 'shell', toolCallId, reason: detail } })
      store.updateRun(runId, { status: 'interrupted', interruptedFrom: 'executing' })
      store.markRunInterrupted(runId, reason)
      throw new Error(reason)
    }
    if (result.commit) {
      store.appendEvent({
        runId,
        type: 'checkpoint.shell',
        agentId: agentId ?? 'head',
        payload: {
          toolCallId,
          commit: result.commit,
          added: changedFiles.added?.length ?? 0,
          modified: changedFiles.modified?.length ?? 0,
          removed: changedFiles.removed?.length ?? 0,
          truncated: Boolean(changedFiles.truncated),
          note: 'changed during this command interval; not proof of causation',
        },
      })
    }
    return result
  }
  return { assertReady, afterWrite, afterShell, baseline, finalize }
}
